### PR TITLE
Added Output to Security Hub Implementation

### PR DESCRIPTION
**Pull request by maira-samtek**

### CODE REVIEW

**Comment by maira-samtek** [comment]
Tested this for both atlassian and Enterprise Jira.
Atlassian Test:
image

image

**Comment by maira-samtek** [comment]
Tested for Enterprise Jira:

image
image

**Review by yonassrobi — APPROVED** [review]
The code LGTM. Have you tested the feature against Enterprise Jira just to be sure the links / JQL works just like Atlassian?

**Comment by maira-samtek** [comment]
> Tested for Enterprise Jira:
> 
> image image


@yonassrobi this is the details for test with Enterprise Jira

**Pull request merged**
